In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
BASE_PATH = Path("../")

REPORTS_PATH = BASE_PATH / "reports"

DATA_PATH = BASE_PATH / "data"

DASHBOARD_PATH = DATA_PATH / "dashboard"

DASHBOARD_PATH.mkdir(
    parents=True,
    exist_ok=True
)

In [4]:
predictions = pd.read_csv(
    REPORTS_PATH / "test_predictions.csv"
)

feature_importance = pd.read_csv(
    REPORTS_PATH / "feature_importance.csv"
)

model_metrics = pd.read_csv(
    REPORTS_PATH / "model_metrics.csv"
)

In [5]:
predictions.head()

,date,family,sales,year,month,day,day_of_week,quarter,week_of_year,is_weekend,...,lag_1,lag_7,lag_30,rolling_mean_7,rolling_mean_30,prediction,error,abs_error,ape,dataset
0,2017-06-01,BEVERAGES,166771.0,2017,6,1,3,2,22,0,...,174304.0,136779.0,200529.0,188653.857143,184453.266667,192416.984475,-25645.984475,25645.984475,15.377964,Test
1,2017-06-02,BEVERAGES,204402.0,2017,6,2,4,2,22,0,...,166771.0,212870.0,188754.0,192938.428571,183328.000000,168343.520769,36058.479231,36058.479231,17.640962,Test
2,2017-06-03,BEVERAGES,278488.0,2017,6,3,5,2,22,1,...,204402.0,212127.0,149629.0,191728.714286,183849.600000,271117.777576,7370.222424,7370.222424,2.646513,Test
3,2017-06-04,BEVERAGES,339352.0,2017,6,4,6,2,22,1,...,278488.0,254132.0,161279.0,201208.857143,188144.900000,291927.958014,47424.041986,47424.041986,13.974882,Test
4,2017-06-05,BEVERAGES,214773.0,2017,6,5,0,2,23,0,...,339352.0,171962.0,233814.0,213383.142857,194080.666667,225109.594234,-10336.594234,10336.594234,4.812800,Test

In [6]:
feature_importance.head()

          Feature    Importance
0  rolling_mean_7  1.304171e+14
1           lag_7  1.107320e+14
2           lag_1  6.448019e+13
3     day_of_week  9.398110e+12
4             day  4.632591e+12

In [7]:
model_metrics

  Metric         Value
0    MAE  10041.816092
1   RMSE  15175.758000
2     R²      0.966833

In [8]:
predictions.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             380 non-null    str
 1   family           380 non-null    str
 2   sales            380 non-null    float64
 3   year             380 non-null    int64
 4   month            380 non-null    int64
 5   day              380 non-null    int64
 6   day_of_week      380 non-null    int64
 7   quarter          380 non-null    int64
 8   week_of_year     380 non-null    int64
 9   is_weekend       380 non-null    int64
 10  month_sin        380 non-null    float64
 11  month_cos        380 non-null    float64
 12  onpromotion      380 non-null    int64
 13  has_promotion    380 non-null    int64
 14  lag_1            380 non-null    float64
 15  lag_7            380 non-null    float64
 16  lag_30           380 non-null    float64
 17  rolling_mean_7   380 non-null    float64
 18  rolling_mean_30  380 non-null    float64
 19  prediction       380 non-null    float64
 20  error            380 non-null    float64
 21  abs_error        380 non-null    float64
 22  ape              380 non-null    float64
 23  dataset          380 non-null    str
dtypes: float64(12), int64(9), str(3)
memory usage: 71.4 KB

In [9]:
predictions.describe()

,sales,year,month,day,day_of_week,quarter,week_of_year,is_weekend,month_sin,month_cos,...,has_promotion,lag_1,lag_7,lag_30,rolling_mean_7,rolling_mean_30,prediction,error,abs_error,ape
count,380.000000,380.0,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,3.800000e+02,380.000000,...,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
mean,138754.237549,2017.0,6.802632,14.223684,3.013158,2.605263,27.355263,0.289474,-3.748734e-01,-0.846668,...,0.997368,139001.500884,140121.503831,140394.390997,139496.196964,139544.874739,136072.915845,2681.321704,10041.816092,7.182849
std,83439.059360,0.0,0.744722,8.698404,2.012451,0.489439,3.161042,0.454116,3.312986e-01,0.182319,...,0.051299,83502.095984,84048.867981,84144.659705,77575.870858,76405.070412,78434.130003,14956.698716,11393.294442,5.967667
min,33693.000000,2017.0,6.000000,1.000000,0.000000,2.000000,22.000000,0.000000,-8.660254e-01,-1.000000,...,0.000000,33693.000000,33693.000000,34485.000000,42306.428571,45782.833333,34913.388254,-48531.194253,67.720707,0.111724
25%,60283.250000,2017.0,6.000000,7.000000,1.000000,2.000000,25.000000,0.000000,-5.000000e-01,-1.000000,...,1.000000,60410.250000,61124.000000,63703.750000,63027.821429,69194.483333,61111.074915,-4794.839635,2605.346533,3.194083
50%,123850.360750,2017.0,7.000000,13.000000,3.000000,3.000000,27.000000,0.000000,-5.000000e-01,-0.866025,...,1.000000,123850.360750,124820.476750,127316.292090,129584.990254,130542.325394,121585.545241,898.062584,6289.085330,5.453709
75%,198976.391750,2017.0,7.000000,21.250000,5.000000,3.000000,30.000000,1.000000,1.224647e-16,-0.866025,...,1.000000,198976.391750,200508.644000,199757.967500,201583.678571,196694.258333,197522.390749,8180.038334,12571.360090,10.121950
max,420484.196000,2017.0,8.000000,31.000000,6.000000,3.000000,33.000000,1.000000,1.224647e-16,-0.500000,...,1.000000,420484.196000,420484.196000,420484.196000,299249.867000,267653.991967,370958.672631,58473.208143,58473.208143,40.999915

In [10]:
predictions.isna().sum()

date               0
family             0
sales              0
year               0
month              0
day                0
day_of_week        0
quarter            0
week_of_year       0
is_weekend         0
month_sin          0
month_cos          0
onpromotion        0
has_promotion      0
lag_1              0
lag_7              0
lag_30             0
rolling_mean_7     0
rolling_mean_30    0
prediction         0
error              0
abs_error          0
ape                0
dataset            0
dtype: int64

In [12]:
predictions.duplicated().sum()

np.int64(0)

In [13]:
predictions["date"] = pd.to_datetime(predictions["date"])

In [14]:
predictions.dtypes

date               datetime64[us]
family                        str
sales                     float64
year                        int64
month                       int64
day                         int64
day_of_week                 int64
quarter                     int64
week_of_year                int64
is_weekend                  int64
month_sin                 float64
month_cos                 float64
onpromotion                 int64
has_promotion               int64
lag_1                     float64
lag_7                     float64
lag_30                    float64
rolling_mean_7            float64
rolling_mean_30           float64
prediction                float64
error                     float64
abs_error                 float64
ape                       float64
dataset                       str
dtype: object

In [15]:
predictions.columns

Index(['date', 'family', 'sales', 'year', 'month', 'day', 'day_of_week',
       'quarter', 'week_of_year', 'is_weekend', 'month_sin', 'month_cos',
       'onpromotion', 'has_promotion', 'lag_1', 'lag_7', 'lag_30',
       'rolling_mean_7', 'rolling_mean_30', 'prediction', 'error', 'abs_error',
       'ape', 'dataset'],
      dtype='str')

In [16]:
dashboard_data = predictions[
    [
        "date",
        "family",
        "sales",
        "prediction",
        "error",
        "abs_error",
        "ape",
        "onpromotion",
        "dataset"
    ]
].copy()

dashboard_data.head()

,date,family,sales,prediction,error,abs_error,ape,onpromotion,dataset
0,2017-06-01,BEVERAGES,166771.0,192416.984475,-25645.984475,25645.984475,15.377964,586,Test
1,2017-06-02,BEVERAGES,204402.0,168343.520769,36058.479231,36058.479231,17.640962,1309,Test
2,2017-06-03,BEVERAGES,278488.0,271117.777576,7370.222424,7370.222424,2.646513,1377,Test
3,2017-06-04,BEVERAGES,339352.0,291927.958014,47424.041986,47424.041986,13.974882,1393,Test
4,2017-06-05,BEVERAGES,214773.0,225109.594234,-10336.594234,10336.594234,4.812800,1253,Test

In [17]:
dashboard_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         380 non-null    datetime64[us]
 1   family       380 non-null    str
 2   sales        380 non-null    float64
 3   prediction   380 non-null    float64
 4   error        380 non-null    float64
 5   abs_error    380 non-null    float64
 6   ape          380 non-null    float64
 7   onpromotion  380 non-null    int64
 8   dataset      380 non-null    str
dtypes: datetime64[us](1), float64(5), int64(1), str(2)
memory usage: 26.8 KB

In [18]:

dashboard_data = dashboard_data.sort_values(
    by=["family", "date"]
).reset_index(drop=True)

dashboard_data.head()

,date,family,sales,prediction,error,abs_error,ape,onpromotion,dataset
0,2017-06-01,BEVERAGES,166771.0,192416.984475,-25645.984475,25645.984475,15.377964,586,Test
1,2017-06-02,BEVERAGES,204402.0,168343.520769,36058.479231,36058.479231,17.640962,1309,Test
2,2017-06-03,BEVERAGES,278488.0,271117.777576,7370.222424,7370.222424,2.646513,1377,Test
3,2017-06-04,BEVERAGES,339352.0,291927.958014,47424.041986,47424.041986,13.974882,1393,Test
4,2017-06-05,BEVERAGES,214773.0,225109.594234,-10336.594234,10336.594234,4.812800,1253,Test

In [19]:
dashboard_data["accuracy"] = (
    100 - dashboard_data["ape"]
)

dashboard_data["accuracy"] = (
    dashboard_data["accuracy"]
    .clip(lower=0, upper=100)
)

In [20]:
numeric_cols = [
    "sales",
    "prediction",
    "error",
    "abs_error",
    "ape",
    "accuracy"
]

dashboard_data[numeric_cols] = (
    dashboard_data[numeric_cols]
    .round(2)
)

In [21]:
dashboard_data.head()

,date,family,sales,prediction,error,abs_error,ape,onpromotion,dataset,accuracy
0,2017-06-01,BEVERAGES,166771.0,192416.98,-25645.98,25645.98,15.38,586,Test,84.62
1,2017-06-02,BEVERAGES,204402.0,168343.52,36058.48,36058.48,17.64,1309,Test,82.36
2,2017-06-03,BEVERAGES,278488.0,271117.78,7370.22,7370.22,2.65,1377,Test,97.35
3,2017-06-04,BEVERAGES,339352.0,291927.96,47424.04,47424.04,13.97,1393,Test,86.03
4,2017-06-05,BEVERAGES,214773.0,225109.59,-10336.59,10336.59,4.81,1253,Test,95.19